"""
Gold-standard, datasheet-verified code templates for LPC2148 peripherals.

These templates are NEVER generated by the LLM - they are injected directly
from this file to guarantee bit-level correctness.
"""

# === PWM =====================================================================
LPC2148_PWM_TEMPLATE = """\
#include <lpc214x.h>

void PWM_Init(void)
{{
    /* Step 1: Select {func} function on {pin} */
    {pinsel_reg} = ({pinsel_reg} & ~({pinsel_mask} << {pinsel_shift})) | ({pinsel_val} << {pinsel_shift});
    PWMPR = 0;
    PWMMR0 = 1000;
    PWMMR{channel} = {duty_ticks};
    PWMMCR = (1 << 1);
    PWMPCR = (1 << {pcr_bit});
    PWMLER = (1 << 0) | (1 << {channel});
    PWMTCR = (1 << 0) | (1 << 3);
}}"""

def get_pwm_config(channel: int, duty_percent: int):
    # Pin Mapping Gold Data
    mapping = {
        1: {"pin": "P0.0", "reg": "PINSEL0", "shift": 0, "mask": 0x3, "val": 0x2, "pcr": 9},
        2: {"pin": "P0.7", "reg": "PINSEL0", "shift": 14, "mask": 0x3, "val": 0x2, "pcr": 10},
        5: {"pin": "P0.21", "reg": "PINSEL1", "shift": 10, "mask": 0x3, "val": 0x1, "pcr": 13},
    }
    m = mapping.get(channel, mapping[1])
    duty_ticks = int(1000 * (duty_percent / 100))
    
    return LPC2148_PWM_TEMPLATE.format(
        func=f"PWM{channel}", pin=m["pin"], pinsel_reg=m["reg"],
        pinsel_shift=m["shift"], pinsel_mask=m["mask"], pinsel_val=m["val"],
        channel=channel if channel in [1,2,3,4,5,6] else 1,
        duty_ticks=duty_ticks, pcr_bit=m["pcr"]
    )

LPC2148_PWM_REGISTER_TABLE = """\
| Register | Address     | Role                                 |
|----------|-------------|--------------------------------------|
| PINSEL0  | 0xE002C000  | Pin function select                  |
| PWMPR    | 0xE001400C  | Prescaler - PCLK divider             |
| PWMMR0   | 0xE0014018  | Period - TC resets here              |
| PWMMR1-6 | 0xE00140xx  | Duty cycle channels                  |
| PWMMCR   | 0xE0014014  | Match control - reset TC on MR0      |
| PWMPCR   | 0xE001404C  | PWM control - enable outputs         |
| PWMLER   | 0xE0014050  | Latch enable - apply MR values       |"""

LPC2148_PWM_PIN_TABLE = """\
| Port Pin | Function   | PINSEL Register | Bit positions | Bit value |
|----------|------------|-----------------|---------------|-----------|
| P0.0     | PWM1       | PINSEL0         | bits [1:0]    | `10` (2)  |
| P0.7     | PWM2       | PINSEL0         | bits [15:14]  | `10` (2)  |
| P0.21    | PWM5       | PINSEL1         | bits [11:10]  | `01` (1)  |"""

# === UART ====================================================================
LPC2148_UART_TEMPLATE = """\
#include <lpc214x.h>

void UART{channel}_Init(void)
{{
    /* Step 1: Configure pins for UART{channel} */
    {pinsel_reg} &= ~({pinsel_mask} << {pinsel_shift});
    {pinsel_reg} |=  ({pinsel_val} << {pinsel_shift});

    /* Step 2: Enable DLAB */
    U{channel}LCR = 0x83;

    /* Step 3: Set Baud Rate ({baud})
       Assumes PCLK = 15MHz (VPB_DIV=4, CCLK=60MHz)
       DLL = PCLK / (16 * baud) = {dll}
       If your PCLK differs, recalculate: DLL = PCLK_Hz / (16 * baud) */
    U{channel}DLL = {dll};
    U{channel}DLM = {dlm};

    /* Step 4: 8N1, Disable DLAB */
    U{channel}LCR = 0x03;
    U{channel}FCR = 0x07;
}}"""

def get_uart_config(channel: int, baud: int):
    # PCLK = CCLK / VPB_DIV. Default VPB_DIV=4, CCLK=60MHz -> PCLK=15MHz
    # If VPB_DIV=1, PCLK=60MHz. Adjust PCLK_HZ if your system differs.
    PCLK_HZ = 15_000_000
    baud_divisors = {b: round(PCLK_HZ / (16 * b)) for b in [9600, 19200, 38400, 57600, 115200]}
    dll = baud_divisors.get(baud, round(PCLK_HZ / (16 * baud)))
    
    mapping = {
        0: {"reg": "PINSEL0", "shift": 0, "mask": 0xF, "val": 0x5},
        1: {"reg": "PINSEL0", "shift": 16, "mask": 0xF, "val": 0x5},
    }
    m = mapping.get(channel, mapping[0])
    
    return LPC2148_UART_TEMPLATE.format(
        channel=channel, baud=baud, dll=dll, dlm=0,
        pinsel_reg=m["reg"], pinsel_shift=m["shift"], 
        pinsel_mask=m["mask"], pinsel_val=m["val"]
    )

LPC2148_UART_REGISTER_TABLE = "| Register | Role | Description |\n|---|---|---|\n| UxLCR | Line Control | DLAB and Frame format |\n| UxDLL/M | Divisor Latch | Baud rate generation |\n| UxLSR | Line Status | Ready checks |"

# === ADC =====================================================================
LPC2148_ADC_TEMPLATE = """\
#include <lpc214x.h>

void ADC_Init(void)
{{
    /* Configure {pin} as AD0.{channel} */
    {pinsel_reg} = ({pinsel_reg} & ~({pinsel_mask} << {pinsel_shift})) | ({pinsel_val} << {pinsel_shift});

    /* AD0CR: Channel {channel}, PDN=1 */
    AD0CR = (1 << {channel}) | (13 << 8) | (1 << 21);
}}"""

def get_adc_config(channel: int):
    mapping = {
        1: {"pin": "P0.28", "reg": "PINSEL1", "shift": 24, "mask": 0x3, "val": 0x1},
        2: {"pin": "P0.29", "reg": "PINSEL1", "shift": 26, "mask": 0x3, "val": 0x1},
    }
    m = mapping.get(channel, mapping[1])
    return LPC2148_ADC_TEMPLATE.format(
        channel=channel, pin=m["pin"], pinsel_reg=m["reg"],
        pinsel_shift=m["shift"], pinsel_mask=m["mask"], pinsel_val=m["val"]
    )

LPC2148_ADC_REGISTER_TABLE = "| Register | Role | Description |\n|---|---|---|\n| AD0CR | Control | Channel and Clock |"

# === SPI =====================================================================
LPC2148_SPI_TEMPLATE = """\
#include <lpc214x.h>

void SPI_Init(void)
{{
    /* Step 1: Configure P0.4=SCK0, P0.5=MISO0, P0.6=MOSI0, P0.7=SSEL0 */
    /* PINSEL0 bits [9:8]=01 (SCK), [11:10]=01 (MISO), [13:12]=01 (MOSI), [15:14]=01 (SSEL) */
    PINSEL0 = (PINSEL0 & ~(0xFF << 8)) | (0x55 << 8);

    /* Step 2: Configure SPI — Master, 8-bit, CPOL=0, CPHA=0
       S0SPCR bit layout (LPC2148 UM10139, Chapter 16):
         Bit  2 (BitEnable) = 1  -> use BITS[11:8] field for transfer size
         Bit  5 (MSTR)      = 1  -> Master mode
         Bits 11:8 (BITS)   = 8  -> 8-bit transfer size (binary 1000)
       Combined: (1<<5)|(1<<2)|(8<<8) = 0x824
       Note: if BitEnable (bit 2) = 0, BITS[11:8] is IGNORED and
             hardware defaults to 8-bit regardless. Always set bit 2
             explicitly to avoid silent misconfiguration. */
    S0SPCR = (1 << 5) | (1 << 2) | (8 << 8); /* 0x824: Master, BitEnable, 8-bit */

    /* Step 3: Set clock divider — SPI clock = PCLK / S0SPCCR */
    /* At PCLK=15MHz, S0SPCCR=8 gives SPI clock = 1.875MHz */
    /* S0SPCCR must be an even number >= 8 (datasheet constraint) */
    S0SPCCR = 8;
}}

uint8_t SPI_Transfer(uint8_t data)
{{
    S0SPDR = data;                    /* Write byte to start transfer */
    while (!(S0SPSR & (1 << 7)));    /* Wait for SPIF (transfer complete, bit 7) */
    return S0SPDR;                    /* Read received byte */
}}"""

def get_spi_config():
    return LPC2148_SPI_TEMPLATE

LPC2148_SPI_REGISTER_TABLE = """\
| Register | Address    | Role                                      |
|----------|------------|-------------------------------------------|
| PINSEL0  | 0xE002C000 | Pin function select (SCK/MISO/MOSI/SSEL)  |
| S0SPCR   | 0xE0020000 | SPI Control Register (master/slave, bits) |
| S0SPSR   | 0xE0020004 | SPI Status Register (SPIF flag)           |
| S0SPDR   | 0xE0020008 | SPI Data Register (TX/RX)                 |
| S0SPCCR  | 0xE002000C | SPI Clock Counter Register (clock divider)|"""

# === I2C =====================================================================
LPC2148_I2C_TEMPLATE = """\
#include <lpc214x.h>

void I2C_Init(void)
{{
    /* Step 1: Configure P0.2=SDA0, P0.3=SCL0 */
    /* PINSEL0 bits [5:4]=01 (SDA), [7:6]=01 (SCL) */
    PINSEL0 = (PINSEL0 & ~(0xF << 4)) | (0x5 << 4);

    /* Step 2: Set I2C clock — 100kHz at PCLK=15MHz */
    /* I2SCLH + I2SCLL = PCLK / I2C_freq = 15000000 / 100000 = 150 */
    I20SCLH = 75;
    I20SCLL = 75;

    /* Step 3: Enable I2C interface */
    I20CONSET = (1 << 6);   /* I2EN bit */
}}

uint8_t I2C_ReadByte(uint8_t dev_addr, uint8_t reg_addr)
{{
    /* START */
    I20CONSET = (1 << 5);           /* STA bit */
    while (!(I20CONSET & (1 << 3))); /* Wait SI */

    /* Send device address + WRITE */
    I20DAT = (dev_addr << 1) | 0;
    I20CONCLR = (1 << 5);           /* Clear STA */
    while (!(I20CONSET & (1 << 3)));

    /* Send register address */
    I20DAT = reg_addr;
    I20CONCLR = (1 << 3);           /* Clear SI */
    while (!(I20CONSET & (1 << 3)));

    /* Repeated START */
    I20CONSET = (1 << 5);
    while (!(I20CONSET & (1 << 3)));

    /* Send device address + READ */
    I20DAT = (dev_addr << 1) | 1;
    I20CONCLR = (1 << 5) | (1 << 3);
    while (!(I20CONSET & (1 << 3)));

    /* Read byte (NACK to signal last byte) */
    I20CONCLR = (1 << 2) | (1 << 3); /* AA=0 (NACK), clear SI */
    while (!(I20CONSET & (1 << 3)));

    uint8_t data = I20DAT;

    /* STOP */
    I20CONSET = (1 << 4);           /* STO bit */
    return data;
}}"""

def get_i2c_config():
    return LPC2148_I2C_TEMPLATE

# === GPIO ====================================================================
LPC2148_GPIO_TEMPLATE = """\
#include <lpc214x.h>

void GPIO_Setup(void)
{{
    /* Configure {pin} as Output */
    IO{port}DIR |= (1 << {pin_num});
}}"""

def get_gpio_config(pin_str: str):
    # Parse "P0.10"
    try:
        parts = pin_str.replace("P", "").split(".")
        port = parts[0]
        pin_num = parts[1]
        return LPC2148_GPIO_TEMPLATE.format(pin=pin_str, port=port, pin_num=pin_num)
    except:
        return "// Invalid Pin Format"
