#ifndef LPC214X_H
#define LPC214X_H
#include <stdint.h>
extern volatile uint32_t U0RBR;
extern volatile uint32_t VICVectAddr;
extern volatile uint32_t PINSEL0;
extern volatile uint32_t U0LCR;
extern volatile uint32_t U0DLL;
extern volatile uint32_t U0IER;
extern volatile uint32_t VICVectAddr6;
extern volatile uint32_t VICVectCntl6;
extern volatile uint32_t VICIntEnable;
extern volatile uint32_t IO0SET;
extern volatile uint32_t IO0CLR;
extern volatile uint32_t IO0PIN;
extern volatile uint32_t T1TC;
extern volatile uint32_t PWMMR1;
extern volatile uint32_t PWMMR2;
extern volatile uint32_t PWMLER;
extern volatile uint32_t IO0DIR;
extern volatile uint32_t PWMMR0;
extern volatile uint32_t PWMMCR;
extern volatile uint32_t PWMPCR;
extern volatile uint32_t PWMTCR;
extern volatile uint32_t T1TCR;
extern volatile uint32_t AD0CR;
extern volatile uint32_t AD0DR1;
extern volatile uint32_t PINSEL1;
extern volatile uint32_t CAN1RID;
extern volatile uint32_t CAN1RFS;
extern volatile uint32_t CAN1RDA;
extern volatile uint32_t CAN1RDB;
extern volatile uint32_t CAN1CMR;
extern volatile uint32_t CAN1MOD;
extern volatile uint32_t CAN1BTR;
extern volatile uint32_t VICVectAddr23;
extern volatile uint32_t VICVectCntl23;
extern volatile uint32_t CAN1IER;
extern volatile uint32_t S0SPCR;
extern volatile uint32_t S0SPCCR;
extern volatile uint32_t S0SPDR;
extern volatile uint32_t S0SPSR;

extern volatile uint32_t EXTINT;
extern volatile uint32_t EXTMODE;
extern volatile uint32_t EXTPOLAR;

extern volatile uint32_t VICVectAddr0;
extern volatile uint32_t VICVectAddr1;
extern volatile uint32_t VICVectAddr2;
extern volatile uint32_t VICVectAddr3;
extern volatile uint32_t VICVectAddr4;
extern volatile uint32_t VICVectAddr5;
extern volatile uint32_t VICVectAddr7;
extern volatile uint32_t VICVectAddr8;
extern volatile uint32_t VICVectAddr9;
extern volatile uint32_t VICVectAddr10;
extern volatile uint32_t VICVectAddr11;
extern volatile uint32_t VICVectAddr12;
extern volatile uint32_t VICVectAddr13;
extern volatile uint32_t VICVectAddr14;
extern volatile uint32_t VICVectAddr15;

extern volatile uint32_t VICVectCntl0;
extern volatile uint32_t VICVectCntl1;
extern volatile uint32_t VICVectCntl2;
extern volatile uint32_t VICVectCntl3;
extern volatile uint32_t VICVectCntl4;
extern volatile uint32_t VICVectCntl5;
extern volatile uint32_t VICVectCntl7;
extern volatile uint32_t VICVectCntl8;
extern volatile uint32_t VICVectCntl9;
extern volatile uint32_t VICVectCntl10;
extern volatile uint32_t VICVectCntl11;
extern volatile uint32_t VICVectCntl12;
extern volatile uint32_t VICVectCntl13;
extern volatile uint32_t VICVectCntl14;
extern volatile uint32_t VICVectCntl15;
#endif
